server:
  port: 9090  # the port on which the gateway runs, you can choose any other port too
spring:
  cloud:
    gateway:
      routes:
        - id: film-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/film/**  # All requests that start with /film/ will be routed to the film-service
        - id: media-service
          uri: http://localhost:8082
          predicates:
            - Path=/film-image-url, /film-image  # Requests for film images will be routed to the media-service
        - id: app
          uri: http://localhost:8080
          predicates:
            - Path=/**  # Catch-all for any other routes not specified above
jwt:
  secret:
    - "zhyttia_cikave_i_motivatsiia_to_ye_sylna"
app-service-url:
  - http://localhost:9090/
